server:
  servlet:
    context-path: /person-ms
  port: 9090
  error:
    include-stacktrace: NEVER

app:
  kafka:
    topic:
      person-topic: "tech.eduardnow.test.person"

spring:
  devtools:
    add-properties:
      false

  datasource:
    url: jdbc:postgresql://postgresdb:5432/person_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: "classpath:db/migration/postgresql"
    schemas: public

  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      cors:
        allowed-methods: "POST,PUT"

logging:
  level:
    web: INFO
    org:
      springframework: INFO