spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS= 25:

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework: DEBUG